-- Create tasks table
CREATE TABLE IF NOT EXISTS public.tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Allow public read/write access for demo / development
CREATE POLICY "Allow public all access on tasks" ON public.tasks
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Insert verification row
INSERT INTO public.tasks (title, status)
VALUES ('Learn Next.js & Supabase MCP', 'completed')
RETURNING *;

-- Verify query
SELECT * FROM public.tasks;
